### ISSUE TITLE
Deploy SDK to CocoaPod and Deploying Resource Bundle

### ISSUE THREAD

**Issue by zz60** [smartcar/ios-sdk#1]
1. Make current repository public
2. Create a new release and publish release
3. Lint the project (pod lib lint)
4. Make a Trunk account 

_Now Trunk isn’t exactly an account; it’s a session. So basically there is no need for a password, just an email.
The process is incredibly simple:
`pod trunk register <Your Email>`
You should quickly get an email from CocoaPods to verify your ‘session’. Verify your account by clicking the link provided in the email. CocoaPods will greet you with friendly message: ACE, YOU ARE SET UP!_

5. Push pod (pod trunk push SmartcarOAuthSDK.podspec)

**Comment by gurpreetatwal** [comment]
@zz60 Is this completed?

**Comment by ramya-s** [comment]
Tracked on asana https://app.asana.com/0/601591838947420/605007862710325/f
