### ISSUE TITLE
Cocoapod doesn't seem to be updated

### ISSUE THREAD

**Issue by morgannewman** [smartcar/ios-sdk#48]
@allisonc07 Looks like the README and/or the whole package didn't get updated/deployed properly. I notice launchAuthFlow Parameters doesn't have the new param. Please investigate. https://cocoapods.org/pods/SmartcarAuth

**Comment by allisonc07** [comment]
was just looking at this before lunch! Looks like it's a deploy issue related to the syntax of our podspec
